# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_transactions_transactions_post(self) -> None:
        """Test case for create_transactions_transactions_post

        Create Transactions
        """
        pass

    def test_delete_transactions_transactions_delete_post(self) -> None:
        """Test case for delete_transactions_transactions_delete_post

        Delete Transactions
        """
        pass

    def test_read_transaction_transactions_fq_txn_link_key_get(self) -> None:
        """Test case for read_transaction_transactions_fq_txn_link_key_get

        Read Transaction
        """
        pass

    def test_read_transactions_transactions_get(self) -> None:
        """Test case for read_transactions_transactions_get

        Read Transactions
        """
        pass

    def test_update_transactions_transactions_patch(self) -> None:
        """Test case for update_transactions_transactions_patch

        Update Transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
