# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.models.create_users_users_post_request_inner import CreateUsersUsersPostRequestInner

class TestCreateUsersUsersPostRequestInner(unittest.TestCase):
    """CreateUsersUsersPostRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUsersUsersPostRequestInner:
        """Test CreateUsersUsersPostRequestInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUsersUsersPostRequestInner`
        """
        model = CreateUsersUsersPostRequestInner()
        if include_optional:
            return CreateUsersUsersPostRequestInner(
                user_email = '',
                app_role = 'Admin',
                last_time_logged_in = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                db_created_by = '',
                db_time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                db_time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CreateUsersUsersPostRequestInner(
                user_email = '',
                db_created_by = '',
        )
        """

    def testCreateUsersUsersPostRequestInner(self):
        """Test CreateUsersUsersPostRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
