# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.root_api import RootApi


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RootApi()

    def tearDown(self) -> None:
        pass

    def test_read_root_get(self) -> None:
        """Test case for read_root_get

        Read Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
