# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_users_users_post(self) -> None:
        """Test case for create_users_users_post

        Create Users
        """
        pass

    def test_delete_users_users_delete_post(self) -> None:
        """Test case for delete_users_users_delete_post

        Delete Users
        """
        pass

    def test_read_user_users_user_email_get(self) -> None:
        """Test case for read_user_users_user_email_get

        Read User
        """
        pass

    def test_read_users_users_get(self) -> None:
        """Test case for read_users_users_get

        Read Users
        """
        pass

    def test_update_users_users_patch(self) -> None:
        """Test case for update_users_users_patch

        Update Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
