# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.joins_api import JoinsApi


class TestJoinsApi(unittest.TestCase):
    """JoinsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JoinsApi()

    def tearDown(self) -> None:
        pass

    def test_read_accounts_with_measures_join_accounts_with_measures_get(self) -> None:
        """Test case for read_accounts_with_measures_join_accounts_with_measures_get

        Read Accounts With Measures
        """
        pass

    def test_read_transactions_with_accounts_join_transactions_with_accounts_get(self) -> None:
        """Test case for read_transactions_with_accounts_join_transactions_with_accounts_get

        Read Transactions With Accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
