# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_orphan_txnlines_services_delete_orphan_txnlines_get(self) -> None:
        """Test case for delete_orphan_txnlines_services_delete_orphan_txnlines_get

        Delete Orphan Txnlines
        """
        pass

    def test_get_cash_balance_services_cash_balance_get(self) -> None:
        """Test case for get_cash_balance_services_cash_balance_get

        Get Cash Balance
        """
        pass

    def test_get_cash_consumption_services_get_cash_consumption_get(self) -> None:
        """Test case for get_cash_consumption_services_get_cash_consumption_get

        Get Cash Consumption
        """
        pass

    def test_refresh_actuals_services_refresh_actuals_get(self) -> None:
        """Test case for refresh_actuals_services_refresh_actuals_get

        Refresh Actuals
        """
        pass

    def test_stage_estimates_to_actuals_services_stage_estimates_to_actuals_get(self) -> None:
        """Test case for stage_estimates_to_actuals_services_stage_estimates_to_actuals_get

        Stage Estimates To Actuals
        """
        pass

    def test_sync_transaction_references_services_sync_txn_references_post(self) -> None:
        """Test case for sync_transaction_references_services_sync_txn_references_post

        Sync Transaction References
        """
        pass


if __name__ == '__main__':
    unittest.main()
