# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.reports_api import ReportsApi


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportsApi()

    def tearDown(self) -> None:
        pass

    def test_get_actuals_by_class_and_account_reports_get_actuals_by_class_and_account_get(self) -> None:
        """Test case for get_actuals_by_class_and_account_reports_get_actuals_by_class_and_account_get

        Get Actuals By Class And Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
