# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.api.class_codes_api import ClassCodesApi


class TestClassCodesApi(unittest.TestCase):
    """ClassCodesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClassCodesApi()

    def tearDown(self) -> None:
        pass

    def test_create_class_codes_class_codes_post(self) -> None:
        """Test case for create_class_codes_class_codes_post

        Create Class Codes
        """
        pass

    def test_delete_class_codes_class_codes_delete_post(self) -> None:
        """Test case for delete_class_codes_class_codes_delete_post

        Delete Class Codes
        """
        pass

    def test_read_class_code_class_codes_list_id_get(self) -> None:
        """Test case for read_class_code_class_codes_list_id_get

        Read Class Code
        """
        pass

    def test_read_class_codes_class_codes_get(self) -> None:
        """Test case for read_class_codes_class_codes_get

        Read Class Codes
        """
        pass

    def test_update_class_codes_class_codes_patch(self) -> None:
        """Test case for update_class_codes_class_codes_patch

        Update Class Codes
        """
        pass


if __name__ == '__main__':
    unittest.main()
