# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.models.class_code_read import ClassCodeRead

class TestClassCodeRead(unittest.TestCase):
    """ClassCodeRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClassCodeRead:
        """Test ClassCodeRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClassCodeRead`
        """
        model = ClassCodeRead()
        if include_optional:
            return ClassCodeRead(
                list_id = '',
                time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                edit_sequence = 56,
                name = '',
                full_name = '',
                is_active = True,
                parent_ref_list_id = '',
                parent_ref_full_name = '',
                sublevel = 56,
                time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = 'ESS-BV',
                db_created_by = '',
                db_time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                db_time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                parent_class_code = finops_client.models.class_code_base.ClassCodeBase(
                    list_id = '', 
                    time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    edit_sequence = 56, 
                    name = '', 
                    full_name = '', 
                    is_active = True, 
                    parent_ref_list_id = '', 
                    parent_ref_full_name = '', 
                    sublevel = 56, 
                    time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    source = 'ESS-BV', 
                    db_created_by = '', 
                    db_time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    db_time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                child_class_codes = [
                    finops_client.models.class_code_base.ClassCodeBase(
                        list_id = '', 
                        time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        edit_sequence = 56, 
                        name = '', 
                        full_name = '', 
                        is_active = True, 
                        parent_ref_list_id = '', 
                        parent_ref_full_name = '', 
                        sublevel = 56, 
                        time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        source = 'ESS-BV', 
                        db_created_by = '', 
                        db_time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        db_time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ClassCodeRead(
        )
        """

    def testClassCodeRead(self):
        """Test ClassCodeRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
