# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finops_client.models.create_measures_measures_post_request_inner import CreateMeasuresMeasuresPostRequestInner

class TestCreateMeasuresMeasuresPostRequestInner(unittest.TestCase):
    """CreateMeasuresMeasuresPostRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMeasuresMeasuresPostRequestInner:
        """Test CreateMeasuresMeasuresPostRequestInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMeasuresMeasuresPostRequestInner`
        """
        model = CreateMeasuresMeasuresPostRequestInner()
        if include_optional:
            return CreateMeasuresMeasuresPostRequestInner(
                measure_id = 56,
                account_ref_list_id = '',
                class_ref_list_id = '',
                period = '',
                measure_type = 'Op Plan',
                currency = 'AED',
                amount = 1.337,
                source = 'ESS-BV',
                db_created_by = '',
                db_time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                db_time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CreateMeasuresMeasuresPostRequestInner(
                measure_id = 56,
                account_ref_list_id = '',
                period = '',
                measure_type = 'Op Plan',
                currency = 'AED',
                amount = 1.337,
                source = 'ESS-BV',
                db_created_by = '',
        )
        """

    def testCreateMeasuresMeasuresPostRequestInner(self):
        """Test CreateMeasuresMeasuresPostRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
