# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import StrictBool, StrictFloat, StrictInt, StrictStr
from typing import List, Optional, Union
from finops_client.models.account_with_measures import AccountWithMeasures
from finops_client.models.accounting_source import AccountingSource
from finops_client.models.cash_flow_classification import CashFlowClassification
from finops_client.models.measure_type import MeasureType
from finops_client.models.statement_level import StatementLevel
from finops_client.models.transaction_with_accounts import TransactionWithAccounts
from finops_client.models.type_of_account import TypeOfAccount

from finops_client.api_client import ApiClient, RequestSerialized
from finops_client.api_response import ApiResponse
from finops_client.rest import RESTResponseType


class JoinsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def read_accounts_with_measures_join_accounts_with_measures_get(
        self,
        skip: Optional[StrictInt] = None,
        limit: Optional[StrictInt] = None,
        measure_id: Optional[List[StrictInt]] = None,
        account_type: Optional[List[TypeOfAccount]] = None,
        account_ref_list_id: Optional[List[StrictStr]] = None,
        name: Optional[List[StrictStr]] = None,
        full_name: Optional[List[StrictStr]] = None,
        is_active: Optional[List[StrictBool]] = None,
        is_intercompany: Optional[List[StrictBool]] = None,
        class_ref_list_id: Optional[List[StrictStr]] = None,
        period: Optional[List[StrictStr]] = None,
        measure_type: Optional[List[MeasureType]] = None,
        currency: Optional[List[StrictStr]] = None,
        amount: Optional[List[Union[StrictFloat, StrictInt]]] = None,
        source: Optional[List[AccountingSource]] = None,
        db_created_by: Optional[List[StrictStr]] = None,
        latest: Optional[StrictBool] = None,
        as_of: Optional[datetime] = None,
        date_field: Optional[StrictStr] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        subscriber: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[AccountWithMeasures]:
        """Read Accounts With Measures


        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param measure_id:
        :type measure_id: List[int]
        :param account_type:
        :type account_type: List[TypeOfAccount]
        :param account_ref_list_id:
        :type account_ref_list_id: List[str]
        :param name:
        :type name: List[str]
        :param full_name:
        :type full_name: List[str]
        :param is_active:
        :type is_active: List[bool]
        :param is_intercompany:
        :type is_intercompany: List[bool]
        :param class_ref_list_id:
        :type class_ref_list_id: List[str]
        :param period:
        :type period: List[str]
        :param measure_type:
        :type measure_type: List[MeasureType]
        :param currency:
        :type currency: List[str]
        :param amount:
        :type amount: List[float]
        :param source:
        :type source: List[AccountingSource]
        :param db_created_by:
        :type db_created_by: List[str]
        :param latest:
        :type latest: bool
        :param as_of:
        :type as_of: datetime
        :param date_field:
        :type date_field: str
        :param start_date:
        :type start_date: datetime
        :param end_date:
        :type end_date: datetime
        :param subscriber:
        :type subscriber: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_accounts_with_measures_join_accounts_with_measures_get_serialize(
            skip=skip,
            limit=limit,
            measure_id=measure_id,
            account_type=account_type,
            account_ref_list_id=account_ref_list_id,
            name=name,
            full_name=full_name,
            is_active=is_active,
            is_intercompany=is_intercompany,
            class_ref_list_id=class_ref_list_id,
            period=period,
            measure_type=measure_type,
            currency=currency,
            amount=amount,
            source=source,
            db_created_by=db_created_by,
            latest=latest,
            as_of=as_of,
            date_field=date_field,
            start_date=start_date,
            end_date=end_date,
            subscriber=subscriber,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[AccountWithMeasures]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_accounts_with_measures_join_accounts_with_measures_get_with_http_info(
        self,
        skip: Optional[StrictInt] = None,
        limit: Optional[StrictInt] = None,
        measure_id: Optional[List[StrictInt]] = None,
        account_type: Optional[List[TypeOfAccount]] = None,
        account_ref_list_id: Optional[List[StrictStr]] = None,
        name: Optional[List[StrictStr]] = None,
        full_name: Optional[List[StrictStr]] = None,
        is_active: Optional[List[StrictBool]] = None,
        is_intercompany: Optional[List[StrictBool]] = None,
        class_ref_list_id: Optional[List[StrictStr]] = None,
        period: Optional[List[StrictStr]] = None,
        measure_type: Optional[List[MeasureType]] = None,
        currency: Optional[List[StrictStr]] = None,
        amount: Optional[List[Union[StrictFloat, StrictInt]]] = None,
        source: Optional[List[AccountingSource]] = None,
        db_created_by: Optional[List[StrictStr]] = None,
        latest: Optional[StrictBool] = None,
        as_of: Optional[datetime] = None,
        date_field: Optional[StrictStr] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        subscriber: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[AccountWithMeasures]]:
        """Read Accounts With Measures


        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param measure_id:
        :type measure_id: List[int]
        :param account_type:
        :type account_type: List[TypeOfAccount]
        :param account_ref_list_id:
        :type account_ref_list_id: List[str]
        :param name:
        :type name: List[str]
        :param full_name:
        :type full_name: List[str]
        :param is_active:
        :type is_active: List[bool]
        :param is_intercompany:
        :type is_intercompany: List[bool]
        :param class_ref_list_id:
        :type class_ref_list_id: List[str]
        :param period:
        :type period: List[str]
        :param measure_type:
        :type measure_type: List[MeasureType]
        :param currency:
        :type currency: List[str]
        :param amount:
        :type amount: List[float]
        :param source:
        :type source: List[AccountingSource]
        :param db_created_by:
        :type db_created_by: List[str]
        :param latest:
        :type latest: bool
        :param as_of:
        :type as_of: datetime
        :param date_field:
        :type date_field: str
        :param start_date:
        :type start_date: datetime
        :param end_date:
        :type end_date: datetime
        :param subscriber:
        :type subscriber: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_accounts_with_measures_join_accounts_with_measures_get_serialize(
            skip=skip,
            limit=limit,
            measure_id=measure_id,
            account_type=account_type,
            account_ref_list_id=account_ref_list_id,
            name=name,
            full_name=full_name,
            is_active=is_active,
            is_intercompany=is_intercompany,
            class_ref_list_id=class_ref_list_id,
            period=period,
            measure_type=measure_type,
            currency=currency,
            amount=amount,
            source=source,
            db_created_by=db_created_by,
            latest=latest,
            as_of=as_of,
            date_field=date_field,
            start_date=start_date,
            end_date=end_date,
            subscriber=subscriber,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[AccountWithMeasures]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_accounts_with_measures_join_accounts_with_measures_get_without_preload_content(
        self,
        skip: Optional[StrictInt] = None,
        limit: Optional[StrictInt] = None,
        measure_id: Optional[List[StrictInt]] = None,
        account_type: Optional[List[TypeOfAccount]] = None,
        account_ref_list_id: Optional[List[StrictStr]] = None,
        name: Optional[List[StrictStr]] = None,
        full_name: Optional[List[StrictStr]] = None,
        is_active: Optional[List[StrictBool]] = None,
        is_intercompany: Optional[List[StrictBool]] = None,
        class_ref_list_id: Optional[List[StrictStr]] = None,
        period: Optional[List[StrictStr]] = None,
        measure_type: Optional[List[MeasureType]] = None,
        currency: Optional[List[StrictStr]] = None,
        amount: Optional[List[Union[StrictFloat, StrictInt]]] = None,
        source: Optional[List[AccountingSource]] = None,
        db_created_by: Optional[List[StrictStr]] = None,
        latest: Optional[StrictBool] = None,
        as_of: Optional[datetime] = None,
        date_field: Optional[StrictStr] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        subscriber: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Read Accounts With Measures


        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param measure_id:
        :type measure_id: List[int]
        :param account_type:
        :type account_type: List[TypeOfAccount]
        :param account_ref_list_id:
        :type account_ref_list_id: List[str]
        :param name:
        :type name: List[str]
        :param full_name:
        :type full_name: List[str]
        :param is_active:
        :type is_active: List[bool]
        :param is_intercompany:
        :type is_intercompany: List[bool]
        :param class_ref_list_id:
        :type class_ref_list_id: List[str]
        :param period:
        :type period: List[str]
        :param measure_type:
        :type measure_type: List[MeasureType]
        :param currency:
        :type currency: List[str]
        :param amount:
        :type amount: List[float]
        :param source:
        :type source: List[AccountingSource]
        :param db_created_by:
        :type db_created_by: List[str]
        :param latest:
        :type latest: bool
        :param as_of:
        :type as_of: datetime
        :param date_field:
        :type date_field: str
        :param start_date:
        :type start_date: datetime
        :param end_date:
        :type end_date: datetime
        :param subscriber:
        :type subscriber: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_accounts_with_measures_join_accounts_with_measures_get_serialize(
            skip=skip,
            limit=limit,
            measure_id=measure_id,
            account_type=account_type,
            account_ref_list_id=account_ref_list_id,
            name=name,
            full_name=full_name,
            is_active=is_active,
            is_intercompany=is_intercompany,
            class_ref_list_id=class_ref_list_id,
            period=period,
            measure_type=measure_type,
            currency=currency,
            amount=amount,
            source=source,
            db_created_by=db_created_by,
            latest=latest,
            as_of=as_of,
            date_field=date_field,
            start_date=start_date,
            end_date=end_date,
            subscriber=subscriber,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[AccountWithMeasures]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_accounts_with_measures_join_accounts_with_measures_get_serialize(
        self,
        skip,
        limit,
        measure_id,
        account_type,
        account_ref_list_id,
        name,
        full_name,
        is_active,
        is_intercompany,
        class_ref_list_id,
        period,
        measure_type,
        currency,
        amount,
        source,
        db_created_by,
        latest,
        as_of,
        date_field,
        start_date,
        end_date,
        subscriber,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'MeasureID': 'multi',
            'AccountType': 'multi',
            'AccountRefListID': 'multi',
            'Name': 'multi',
            'FullName': 'multi',
            'IsActive': 'multi',
            'IsIntercompany': 'multi',
            'ClassRefListID': 'multi',
            'Period': 'multi',
            'MeasureType': 'multi',
            'Currency': 'multi',
            'Amount': 'multi',
            'Source': 'multi',
            'DbCreatedBy': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if skip is not None:
            
            _query_params.append(('skip', skip))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if measure_id is not None:
            
            _query_params.append(('MeasureID', measure_id))
            
        if account_type is not None:
            
            _query_params.append(('AccountType', account_type))
            
        if account_ref_list_id is not None:
            
            _query_params.append(('AccountRefListID', account_ref_list_id))
            
        if name is not None:
            
            _query_params.append(('Name', name))
            
        if full_name is not None:
            
            _query_params.append(('FullName', full_name))
            
        if is_active is not None:
            
            _query_params.append(('IsActive', is_active))
            
        if is_intercompany is not None:
            
            _query_params.append(('IsIntercompany', is_intercompany))
            
        if class_ref_list_id is not None:
            
            _query_params.append(('ClassRefListID', class_ref_list_id))
            
        if period is not None:
            
            _query_params.append(('Period', period))
            
        if measure_type is not None:
            
            _query_params.append(('MeasureType', measure_type))
            
        if currency is not None:
            
            _query_params.append(('Currency', currency))
            
        if amount is not None:
            
            _query_params.append(('Amount', amount))
            
        if source is not None:
            
            _query_params.append(('Source', source))
            
        if db_created_by is not None:
            
            _query_params.append(('DbCreatedBy', db_created_by))
            
        if latest is not None:
            
            _query_params.append(('latest', latest))
            
        if as_of is not None:
            if isinstance(as_of, datetime):
                _query_params.append(
                    (
                        'as_of',
                        as_of.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('as_of', as_of))
            
        if date_field is not None:
            
            _query_params.append(('date_field', date_field))
            
        if start_date is not None:
            if isinstance(start_date, datetime):
                _query_params.append(
                    (
                        'start_date',
                        start_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('start_date', start_date))
            
        if end_date is not None:
            if isinstance(end_date, datetime):
                _query_params.append(
                    (
                        'end_date',
                        end_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('end_date', end_date))
            
        if subscriber is not None:
            
            _query_params.append(('subscriber', subscriber))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/join/accounts_with_measures/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def read_transactions_with_accounts_join_transactions_with_accounts_get(
        self,
        skip: Optional[StrictInt] = None,
        limit: Optional[StrictInt] = None,
        fq_primary_key: Optional[List[Optional[StrictStr]]] = None,
        txn_type: Optional[List[Optional[StrictStr]]] = None,
        txn_id: Optional[List[Optional[StrictStr]]] = None,
        txn_line_id: Optional[List[Optional[StrictStr]]] = None,
        entity_ref_list_id: Optional[List[Optional[StrictStr]]] = None,
        entity_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        txn_date: Optional[List[Optional[datetime]]] = None,
        account_ref_list_id: Optional[List[StrictStr]] = None,
        account_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        class_ref_list_id: Optional[List[StrictStr]] = None,
        class_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        ref_number: Optional[List[Optional[StrictStr]]] = None,
        amount: Optional[List[Union[StrictFloat, StrictInt]]] = None,
        memo: Optional[List[Optional[StrictStr]]] = None,
        fq_txn_link_key: Optional[List[Optional[StrictStr]]] = None,
        fq_journal_entry_link_key: Optional[List[Optional[StrictStr]]] = None,
        source: Optional[List[AccountingSource]] = None,
        list_id: Optional[List[StrictStr]] = None,
        parent_ref_list_id: Optional[List[StrictStr]] = None,
        sublevel: Optional[List[StrictInt]] = None,
        account_type: Optional[List[TypeOfAccount]] = None,
        name: Optional[List[StrictStr]] = None,
        full_name: Optional[List[StrictStr]] = None,
        statement_level: Optional[List[StatementLevel]] = None,
        is_active: Optional[List[StrictBool]] = None,
        is_intercompany: Optional[List[StrictBool]] = None,
        default_currency: Optional[List[StrictStr]] = None,
        cash_flow_classification: Optional[List[CashFlowClassification]] = None,
        db_created_by: Optional[List[StrictStr]] = None,
        date_field: Optional[StrictStr] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        subscriber: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[TransactionWithAccounts]:
        """Read Transactions With Accounts


        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param fq_primary_key:
        :type fq_primary_key: List[Optional[str]]
        :param txn_type:
        :type txn_type: List[Optional[str]]
        :param txn_id:
        :type txn_id: List[Optional[str]]
        :param txn_line_id:
        :type txn_line_id: List[Optional[str]]
        :param entity_ref_list_id:
        :type entity_ref_list_id: List[Optional[str]]
        :param entity_ref_full_name:
        :type entity_ref_full_name: List[Optional[str]]
        :param txn_date:
        :type txn_date: List[Optional[datetime]]
        :param account_ref_list_id:
        :type account_ref_list_id: List[str]
        :param account_ref_full_name:
        :type account_ref_full_name: List[Optional[str]]
        :param class_ref_list_id:
        :type class_ref_list_id: List[str]
        :param class_ref_full_name:
        :type class_ref_full_name: List[Optional[str]]
        :param ref_number:
        :type ref_number: List[Optional[str]]
        :param amount:
        :type amount: List[float]
        :param memo:
        :type memo: List[Optional[str]]
        :param fq_txn_link_key:
        :type fq_txn_link_key: List[Optional[str]]
        :param fq_journal_entry_link_key:
        :type fq_journal_entry_link_key: List[Optional[str]]
        :param source:
        :type source: List[AccountingSource]
        :param list_id:
        :type list_id: List[str]
        :param parent_ref_list_id:
        :type parent_ref_list_id: List[str]
        :param sublevel:
        :type sublevel: List[int]
        :param account_type:
        :type account_type: List[TypeOfAccount]
        :param name:
        :type name: List[str]
        :param full_name:
        :type full_name: List[str]
        :param statement_level:
        :type statement_level: List[StatementLevel]
        :param is_active:
        :type is_active: List[bool]
        :param is_intercompany:
        :type is_intercompany: List[bool]
        :param default_currency:
        :type default_currency: List[str]
        :param cash_flow_classification:
        :type cash_flow_classification: List[CashFlowClassification]
        :param db_created_by:
        :type db_created_by: List[str]
        :param date_field:
        :type date_field: str
        :param start_date:
        :type start_date: datetime
        :param end_date:
        :type end_date: datetime
        :param subscriber:
        :type subscriber: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_transactions_with_accounts_join_transactions_with_accounts_get_serialize(
            skip=skip,
            limit=limit,
            fq_primary_key=fq_primary_key,
            txn_type=txn_type,
            txn_id=txn_id,
            txn_line_id=txn_line_id,
            entity_ref_list_id=entity_ref_list_id,
            entity_ref_full_name=entity_ref_full_name,
            txn_date=txn_date,
            account_ref_list_id=account_ref_list_id,
            account_ref_full_name=account_ref_full_name,
            class_ref_list_id=class_ref_list_id,
            class_ref_full_name=class_ref_full_name,
            ref_number=ref_number,
            amount=amount,
            memo=memo,
            fq_txn_link_key=fq_txn_link_key,
            fq_journal_entry_link_key=fq_journal_entry_link_key,
            source=source,
            list_id=list_id,
            parent_ref_list_id=parent_ref_list_id,
            sublevel=sublevel,
            account_type=account_type,
            name=name,
            full_name=full_name,
            statement_level=statement_level,
            is_active=is_active,
            is_intercompany=is_intercompany,
            default_currency=default_currency,
            cash_flow_classification=cash_flow_classification,
            db_created_by=db_created_by,
            date_field=date_field,
            start_date=start_date,
            end_date=end_date,
            subscriber=subscriber,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[TransactionWithAccounts]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_transactions_with_accounts_join_transactions_with_accounts_get_with_http_info(
        self,
        skip: Optional[StrictInt] = None,
        limit: Optional[StrictInt] = None,
        fq_primary_key: Optional[List[Optional[StrictStr]]] = None,
        txn_type: Optional[List[Optional[StrictStr]]] = None,
        txn_id: Optional[List[Optional[StrictStr]]] = None,
        txn_line_id: Optional[List[Optional[StrictStr]]] = None,
        entity_ref_list_id: Optional[List[Optional[StrictStr]]] = None,
        entity_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        txn_date: Optional[List[Optional[datetime]]] = None,
        account_ref_list_id: Optional[List[StrictStr]] = None,
        account_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        class_ref_list_id: Optional[List[StrictStr]] = None,
        class_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        ref_number: Optional[List[Optional[StrictStr]]] = None,
        amount: Optional[List[Union[StrictFloat, StrictInt]]] = None,
        memo: Optional[List[Optional[StrictStr]]] = None,
        fq_txn_link_key: Optional[List[Optional[StrictStr]]] = None,
        fq_journal_entry_link_key: Optional[List[Optional[StrictStr]]] = None,
        source: Optional[List[AccountingSource]] = None,
        list_id: Optional[List[StrictStr]] = None,
        parent_ref_list_id: Optional[List[StrictStr]] = None,
        sublevel: Optional[List[StrictInt]] = None,
        account_type: Optional[List[TypeOfAccount]] = None,
        name: Optional[List[StrictStr]] = None,
        full_name: Optional[List[StrictStr]] = None,
        statement_level: Optional[List[StatementLevel]] = None,
        is_active: Optional[List[StrictBool]] = None,
        is_intercompany: Optional[List[StrictBool]] = None,
        default_currency: Optional[List[StrictStr]] = None,
        cash_flow_classification: Optional[List[CashFlowClassification]] = None,
        db_created_by: Optional[List[StrictStr]] = None,
        date_field: Optional[StrictStr] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        subscriber: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[TransactionWithAccounts]]:
        """Read Transactions With Accounts


        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param fq_primary_key:
        :type fq_primary_key: List[Optional[str]]
        :param txn_type:
        :type txn_type: List[Optional[str]]
        :param txn_id:
        :type txn_id: List[Optional[str]]
        :param txn_line_id:
        :type txn_line_id: List[Optional[str]]
        :param entity_ref_list_id:
        :type entity_ref_list_id: List[Optional[str]]
        :param entity_ref_full_name:
        :type entity_ref_full_name: List[Optional[str]]
        :param txn_date:
        :type txn_date: List[Optional[datetime]]
        :param account_ref_list_id:
        :type account_ref_list_id: List[str]
        :param account_ref_full_name:
        :type account_ref_full_name: List[Optional[str]]
        :param class_ref_list_id:
        :type class_ref_list_id: List[str]
        :param class_ref_full_name:
        :type class_ref_full_name: List[Optional[str]]
        :param ref_number:
        :type ref_number: List[Optional[str]]
        :param amount:
        :type amount: List[float]
        :param memo:
        :type memo: List[Optional[str]]
        :param fq_txn_link_key:
        :type fq_txn_link_key: List[Optional[str]]
        :param fq_journal_entry_link_key:
        :type fq_journal_entry_link_key: List[Optional[str]]
        :param source:
        :type source: List[AccountingSource]
        :param list_id:
        :type list_id: List[str]
        :param parent_ref_list_id:
        :type parent_ref_list_id: List[str]
        :param sublevel:
        :type sublevel: List[int]
        :param account_type:
        :type account_type: List[TypeOfAccount]
        :param name:
        :type name: List[str]
        :param full_name:
        :type full_name: List[str]
        :param statement_level:
        :type statement_level: List[StatementLevel]
        :param is_active:
        :type is_active: List[bool]
        :param is_intercompany:
        :type is_intercompany: List[bool]
        :param default_currency:
        :type default_currency: List[str]
        :param cash_flow_classification:
        :type cash_flow_classification: List[CashFlowClassification]
        :param db_created_by:
        :type db_created_by: List[str]
        :param date_field:
        :type date_field: str
        :param start_date:
        :type start_date: datetime
        :param end_date:
        :type end_date: datetime
        :param subscriber:
        :type subscriber: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_transactions_with_accounts_join_transactions_with_accounts_get_serialize(
            skip=skip,
            limit=limit,
            fq_primary_key=fq_primary_key,
            txn_type=txn_type,
            txn_id=txn_id,
            txn_line_id=txn_line_id,
            entity_ref_list_id=entity_ref_list_id,
            entity_ref_full_name=entity_ref_full_name,
            txn_date=txn_date,
            account_ref_list_id=account_ref_list_id,
            account_ref_full_name=account_ref_full_name,
            class_ref_list_id=class_ref_list_id,
            class_ref_full_name=class_ref_full_name,
            ref_number=ref_number,
            amount=amount,
            memo=memo,
            fq_txn_link_key=fq_txn_link_key,
            fq_journal_entry_link_key=fq_journal_entry_link_key,
            source=source,
            list_id=list_id,
            parent_ref_list_id=parent_ref_list_id,
            sublevel=sublevel,
            account_type=account_type,
            name=name,
            full_name=full_name,
            statement_level=statement_level,
            is_active=is_active,
            is_intercompany=is_intercompany,
            default_currency=default_currency,
            cash_flow_classification=cash_flow_classification,
            db_created_by=db_created_by,
            date_field=date_field,
            start_date=start_date,
            end_date=end_date,
            subscriber=subscriber,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[TransactionWithAccounts]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_transactions_with_accounts_join_transactions_with_accounts_get_without_preload_content(
        self,
        skip: Optional[StrictInt] = None,
        limit: Optional[StrictInt] = None,
        fq_primary_key: Optional[List[Optional[StrictStr]]] = None,
        txn_type: Optional[List[Optional[StrictStr]]] = None,
        txn_id: Optional[List[Optional[StrictStr]]] = None,
        txn_line_id: Optional[List[Optional[StrictStr]]] = None,
        entity_ref_list_id: Optional[List[Optional[StrictStr]]] = None,
        entity_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        txn_date: Optional[List[Optional[datetime]]] = None,
        account_ref_list_id: Optional[List[StrictStr]] = None,
        account_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        class_ref_list_id: Optional[List[StrictStr]] = None,
        class_ref_full_name: Optional[List[Optional[StrictStr]]] = None,
        ref_number: Optional[List[Optional[StrictStr]]] = None,
        amount: Optional[List[Union[StrictFloat, StrictInt]]] = None,
        memo: Optional[List[Optional[StrictStr]]] = None,
        fq_txn_link_key: Optional[List[Optional[StrictStr]]] = None,
        fq_journal_entry_link_key: Optional[List[Optional[StrictStr]]] = None,
        source: Optional[List[AccountingSource]] = None,
        list_id: Optional[List[StrictStr]] = None,
        parent_ref_list_id: Optional[List[StrictStr]] = None,
        sublevel: Optional[List[StrictInt]] = None,
        account_type: Optional[List[TypeOfAccount]] = None,
        name: Optional[List[StrictStr]] = None,
        full_name: Optional[List[StrictStr]] = None,
        statement_level: Optional[List[StatementLevel]] = None,
        is_active: Optional[List[StrictBool]] = None,
        is_intercompany: Optional[List[StrictBool]] = None,
        default_currency: Optional[List[StrictStr]] = None,
        cash_flow_classification: Optional[List[CashFlowClassification]] = None,
        db_created_by: Optional[List[StrictStr]] = None,
        date_field: Optional[StrictStr] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        subscriber: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Read Transactions With Accounts


        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param fq_primary_key:
        :type fq_primary_key: List[Optional[str]]
        :param txn_type:
        :type txn_type: List[Optional[str]]
        :param txn_id:
        :type txn_id: List[Optional[str]]
        :param txn_line_id:
        :type txn_line_id: List[Optional[str]]
        :param entity_ref_list_id:
        :type entity_ref_list_id: List[Optional[str]]
        :param entity_ref_full_name:
        :type entity_ref_full_name: List[Optional[str]]
        :param txn_date:
        :type txn_date: List[Optional[datetime]]
        :param account_ref_list_id:
        :type account_ref_list_id: List[str]
        :param account_ref_full_name:
        :type account_ref_full_name: List[Optional[str]]
        :param class_ref_list_id:
        :type class_ref_list_id: List[str]
        :param class_ref_full_name:
        :type class_ref_full_name: List[Optional[str]]
        :param ref_number:
        :type ref_number: List[Optional[str]]
        :param amount:
        :type amount: List[float]
        :param memo:
        :type memo: List[Optional[str]]
        :param fq_txn_link_key:
        :type fq_txn_link_key: List[Optional[str]]
        :param fq_journal_entry_link_key:
        :type fq_journal_entry_link_key: List[Optional[str]]
        :param source:
        :type source: List[AccountingSource]
        :param list_id:
        :type list_id: List[str]
        :param parent_ref_list_id:
        :type parent_ref_list_id: List[str]
        :param sublevel:
        :type sublevel: List[int]
        :param account_type:
        :type account_type: List[TypeOfAccount]
        :param name:
        :type name: List[str]
        :param full_name:
        :type full_name: List[str]
        :param statement_level:
        :type statement_level: List[StatementLevel]
        :param is_active:
        :type is_active: List[bool]
        :param is_intercompany:
        :type is_intercompany: List[bool]
        :param default_currency:
        :type default_currency: List[str]
        :param cash_flow_classification:
        :type cash_flow_classification: List[CashFlowClassification]
        :param db_created_by:
        :type db_created_by: List[str]
        :param date_field:
        :type date_field: str
        :param start_date:
        :type start_date: datetime
        :param end_date:
        :type end_date: datetime
        :param subscriber:
        :type subscriber: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_transactions_with_accounts_join_transactions_with_accounts_get_serialize(
            skip=skip,
            limit=limit,
            fq_primary_key=fq_primary_key,
            txn_type=txn_type,
            txn_id=txn_id,
            txn_line_id=txn_line_id,
            entity_ref_list_id=entity_ref_list_id,
            entity_ref_full_name=entity_ref_full_name,
            txn_date=txn_date,
            account_ref_list_id=account_ref_list_id,
            account_ref_full_name=account_ref_full_name,
            class_ref_list_id=class_ref_list_id,
            class_ref_full_name=class_ref_full_name,
            ref_number=ref_number,
            amount=amount,
            memo=memo,
            fq_txn_link_key=fq_txn_link_key,
            fq_journal_entry_link_key=fq_journal_entry_link_key,
            source=source,
            list_id=list_id,
            parent_ref_list_id=parent_ref_list_id,
            sublevel=sublevel,
            account_type=account_type,
            name=name,
            full_name=full_name,
            statement_level=statement_level,
            is_active=is_active,
            is_intercompany=is_intercompany,
            default_currency=default_currency,
            cash_flow_classification=cash_flow_classification,
            db_created_by=db_created_by,
            date_field=date_field,
            start_date=start_date,
            end_date=end_date,
            subscriber=subscriber,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[TransactionWithAccounts]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_transactions_with_accounts_join_transactions_with_accounts_get_serialize(
        self,
        skip,
        limit,
        fq_primary_key,
        txn_type,
        txn_id,
        txn_line_id,
        entity_ref_list_id,
        entity_ref_full_name,
        txn_date,
        account_ref_list_id,
        account_ref_full_name,
        class_ref_list_id,
        class_ref_full_name,
        ref_number,
        amount,
        memo,
        fq_txn_link_key,
        fq_journal_entry_link_key,
        source,
        list_id,
        parent_ref_list_id,
        sublevel,
        account_type,
        name,
        full_name,
        statement_level,
        is_active,
        is_intercompany,
        default_currency,
        cash_flow_classification,
        db_created_by,
        date_field,
        start_date,
        end_date,
        subscriber,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'FQPrimaryKey': 'multi',
            'TxnType': 'multi',
            'TxnID': 'multi',
            'TxnLineID': 'multi',
            'EntityRefListID': 'multi',
            'EntityRefFullName': 'multi',
            'TxnDate': 'multi',
            'AccountRefListID': 'multi',
            'AccountRefFullName': 'multi',
            'ClassRefListID': 'multi',
            'ClassRefFullName': 'multi',
            'RefNumber': 'multi',
            'Amount': 'multi',
            'Memo': 'multi',
            'FQTxnLinkKey': 'multi',
            'FQJournalEntryLinkKey': 'multi',
            'Source': 'multi',
            'ListID': 'multi',
            'ParentRefListID': 'multi',
            'Sublevel': 'multi',
            'AccountType': 'multi',
            'Name': 'multi',
            'FullName': 'multi',
            'StatementLevel': 'multi',
            'IsActive': 'multi',
            'IsIntercompany': 'multi',
            'DefaultCurrency': 'multi',
            'CashFlowClassification': 'multi',
            'DbCreatedBy': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if skip is not None:
            
            _query_params.append(('skip', skip))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if fq_primary_key is not None:
            
            _query_params.append(('FQPrimaryKey', fq_primary_key))
            
        if txn_type is not None:
            
            _query_params.append(('TxnType', txn_type))
            
        if txn_id is not None:
            
            _query_params.append(('TxnID', txn_id))
            
        if txn_line_id is not None:
            
            _query_params.append(('TxnLineID', txn_line_id))
            
        if entity_ref_list_id is not None:
            
            _query_params.append(('EntityRefListID', entity_ref_list_id))
            
        if entity_ref_full_name is not None:
            
            _query_params.append(('EntityRefFullName', entity_ref_full_name))
            
        if txn_date is not None:
            
            _query_params.append(('TxnDate', txn_date))
            
        if account_ref_list_id is not None:
            
            _query_params.append(('AccountRefListID', account_ref_list_id))
            
        if account_ref_full_name is not None:
            
            _query_params.append(('AccountRefFullName', account_ref_full_name))
            
        if class_ref_list_id is not None:
            
            _query_params.append(('ClassRefListID', class_ref_list_id))
            
        if class_ref_full_name is not None:
            
            _query_params.append(('ClassRefFullName', class_ref_full_name))
            
        if ref_number is not None:
            
            _query_params.append(('RefNumber', ref_number))
            
        if amount is not None:
            
            _query_params.append(('Amount', amount))
            
        if memo is not None:
            
            _query_params.append(('Memo', memo))
            
        if fq_txn_link_key is not None:
            
            _query_params.append(('FQTxnLinkKey', fq_txn_link_key))
            
        if fq_journal_entry_link_key is not None:
            
            _query_params.append(('FQJournalEntryLinkKey', fq_journal_entry_link_key))
            
        if source is not None:
            
            _query_params.append(('Source', source))
            
        if list_id is not None:
            
            _query_params.append(('ListID', list_id))
            
        if parent_ref_list_id is not None:
            
            _query_params.append(('ParentRefListID', parent_ref_list_id))
            
        if sublevel is not None:
            
            _query_params.append(('Sublevel', sublevel))
            
        if account_type is not None:
            
            _query_params.append(('AccountType', account_type))
            
        if name is not None:
            
            _query_params.append(('Name', name))
            
        if full_name is not None:
            
            _query_params.append(('FullName', full_name))
            
        if statement_level is not None:
            
            _query_params.append(('StatementLevel', statement_level))
            
        if is_active is not None:
            
            _query_params.append(('IsActive', is_active))
            
        if is_intercompany is not None:
            
            _query_params.append(('IsIntercompany', is_intercompany))
            
        if default_currency is not None:
            
            _query_params.append(('DefaultCurrency', default_currency))
            
        if cash_flow_classification is not None:
            
            _query_params.append(('CashFlowClassification', cash_flow_classification))
            
        if db_created_by is not None:
            
            _query_params.append(('DbCreatedBy', db_created_by))
            
        if date_field is not None:
            
            _query_params.append(('date_field', date_field))
            
        if start_date is not None:
            if isinstance(start_date, datetime):
                _query_params.append(
                    (
                        'start_date',
                        start_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('start_date', start_date))
            
        if end_date is not None:
            if isinstance(end_date, datetime):
                _query_params.append(
                    (
                        'end_date',
                        end_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('end_date', end_date))
            
        if subscriber is not None:
            
            _query_params.append(('subscriber', subscriber))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/join/transactions_with_accounts/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


