# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from finops_client.models.accounting_source import AccountingSource
from finops_client.models.type_of_account import TypeOfAccount
from typing import Optional, Set
from typing_extensions import Self

class PeriodAmount(BaseModel):
    """
    PeriodAmount
    """ # noqa: E501
    source: AccountingSource = Field(alias="Source")
    account_type: TypeOfAccount = Field(alias="AccountType")
    class_full_name: Optional[StrictStr] = Field(default=None, alias="ClassFullName")
    account_full_name: StrictStr = Field(alias="AccountFullName")
    period: StrictStr = Field(alias="Period")
    total_amount: Union[StrictFloat, StrictInt] = Field(alias="TotalAmount")
    __properties: ClassVar[List[str]] = ["Source", "AccountType", "ClassFullName", "AccountFullName", "Period", "TotalAmount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeriodAmount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if class_full_name (nullable) is None
        # and model_fields_set contains the field
        if self.class_full_name is None and "class_full_name" in self.model_fields_set:
            _dict['ClassFullName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeriodAmount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Source": obj.get("Source"),
            "AccountType": obj.get("AccountType"),
            "ClassFullName": obj.get("ClassFullName"),
            "AccountFullName": obj.get("AccountFullName"),
            "Period": obj.get("Period"),
            "TotalAmount": obj.get("TotalAmount")
        })
        return _obj


